### ISSUE TITLE
Add History List/ react-router

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/capstone-project#10]
# Add  Router - Create List Overview 

## Value statement
As a **user** 
I need **to have a list of all the stored informations**
so that **get the information I have saved**
----

## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ] A  page with  list of history evaluations school be displayed  in a new window
---

## Tasks

- [ ] Install and incorporate React Router
- [ ] Create a list with collapsed evaluation cards
- [ ] Create general styling 
- [ ] Test in mobile and desktop view

## Size
Medium
