### ISSUE TITLE
Create Sliding /toggle menu 

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/capstone-project#14]
# Create Sliding /toggle menu 

## Value statement
As a **user**
I need **to have s menu screen**
so that **I can jump between different pages**
----
## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ] Add  a burger button on the Form/input page for opening the menu  slide window
 - [ ]   a new screen has to appear (slide in from right to rleft when menu button is clicked
- [ ] a list of all the links has to be listed inside the menu screen

---

## Tasks
- [ ] Create a  vertical positioned  list with links
- [ ] General styling  according to  the approved design
- [ ] Test in mobile and desktop view

## Size
Medium
