### ISSUE TITLE
Toggle Menu

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/capstone-project#2]
Value statement
As a **user**
I need **to have s menu screen**
so that **I can jump between different windows**
----
## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ]  a new screen has to appear (slide in from left to right) when menu button is clicked
- [ ] a list of all the links has to be listed inside the menu screen

---

## Tasks
- [ ] Create a  vertical positioned  list with links 
- [ ] Add toggle logic  to the menu button
- [ ] General styling  according to  the approved design
- [ ] Test in mobile and desktop view

## Size
Medium
