### ISSUE TITLE
Information input

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/capstone-project#7]
Create Information Input
## Value statement

As a user
I need to gather information about the olive oil  I’m tasting
so that I can recognise the difference between all varieties 
----

## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ] 5 Input  fields for listed information :
 1. the name of the producer, 
 2. region,  
 3. vintage, 
 4. classification
 5. cultivars
---

## Tasks
- [ ] Create 5 Input fields accompanied with labels 
- [ ] General styling  according to  the approved design
- [ ] Test in mobile and desktop view

## Size
Medium
